version: '2'
services:
  mongodb:
    image: "tutum/mongodb:3.2"
    # ports:
    #  - "27017:27017"
    #  - "27018:27018"
    environment:
     - AUTH=no
  logic:
    image: "samurais/ss-spa:latest"
    command: "node app.js"
    ports:
    # access logic web testclient from 3001
     - "3001:3001"
    depends_on:
     - mongodb
    links:
     - mongodb
    environment:
     - MONGO_DB_URI=mongodb://mongodb/SuperScriptSPA
     - DEBUG=ss-spa*
