version: '2'
services:
  client:
    image: "samurais/ss-wechaty:latest"
    command: "node app.js"
    depends_on:
     - logic
    links:
     - logic
    environment:
     - WS_SERVER_HOSTNAME=logic